# Generated by Django 2.1.5 on 2019-01-25 09:48

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('a', 'Archive')], default='d', help_text='Select the post status', max_length=1, verbose_name='Status')),
                ('summary', models.TextField(blank=True, help_text='Enter the brief description', max_length=501)),
                ('summary_ru', models.TextField(blank=True, help_text='Enter the brief description', max_length=501, null=True)),
                ('summary_en', models.TextField(blank=True, help_text='Enter the brief description', max_length=501, null=True)),
                ('head_image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Upload the image file', upload_to='pages/%Y/%m/%d')),
                ('content', models.TextField(blank=True, help_text='Enter the page content')),
                ('content_ru', models.TextField(blank=True, help_text='Enter the page content', null=True)),
                ('content_en', models.TextField(blank=True, help_text='Enter the page content', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
