# Generated by Django 2.1.5 on 2019-01-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter the brief description', max_length=501),
        ),
    ]
